dataset_mixer:
    # Approximate Tulu V2 datasets
    # natolambert/tulu-v2-sft-mixture-flan: 50000
    # natolambert/tulu-v2-sft-mixture-cot: 49747
    # allenai/openassistant-guanaco-reformatted: 7708  # not exact subset
    # Vtuber-plan/sharegpt-cleaned: 114046  # original https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered
    # vicgalle/alpaca-gpt4: 20000
    # HuggingFaceH4/CodeAlpaca_20K: 18000  # original uses https://github.com/sahil280114/codealpaca
    # natolambert/tulu-v2-sft-mixture-lima: 1018  # original has 1030
    # WizardLMTeam/WizardLM_evol_instruct_V2_196k: 30000
    # Open-Orca/OpenOrca: 30000
    # natolambert/tulu-v2-sft-mixture-science: 7468  # original data slightly different
    # ai2-adapt-dev/tulu_hard_coded_examples: 14  # the original data replicates this for multiple times
    # Tulu V3.2 preview added by Jacob
    # HuggingFaceH4/no_robots: 9500 # all
    # ai2-adapt-dev/metamath-qa-reformat: 100000
    # ai2-adapt-dev/codefeedback-single-turn-reformat: 156526 # all
    # nvidia/Daring-Anteater: 99532 # all
    # Mix in some new datasets
    # ai2-adapt-dev/slim-orca-300k: 100000
    # AI-MO/NuminaMath-TIR: 72441
    # ai2-adapt-dev/WildChat-1M-Full-GPT4-Only: 200000

    # TBD datasets

    # Datasets to regenerate responses for
    nvidia/Daring-Anteater: 99532 # all
    ai2-adapt-dev/WildChat-1M-Full-GPT4-Only: 100000 # all
    HuggingFaceH4/no_robots: 9500 # all
    ai2-adapt-dev/SlimOrca-reformat: 100000

    # Datasets to keep static
    # ai2-adapt-dev/metamath-qa-reformat: 100000
    # AI-MO/NuminaMath-CoT: 100000
    # m-a-p/CodeFeedback-Filtered-Instruction: 156526