dataset_mixer:
    # ------------------------------------------------------
    # no_robot dataset, human written, for general chat. 
    # Total: 9500
    # Pro: created by scale ai with high cost, should be high quality.
    # Con: small, not diverse enough, may not be in consistent style.
    HuggingFaceH4/no_robots: 9500
    # ------------------------------------------------------
    # OpenAssistant dataset, human written, for general chat.
    # Here, only the highest rated paths are extracted.
    # Total: 7708
    # Pro: created and reviewed by human volunteers, has multi-turn chat.
    # Con: small, still has some noise, the writting quality may not be as good/careful as paid workers, style consistency.
    # TODO: need to check if this version corresponds to the highest rated paths.
    allenai/openassistant-guanaco-reformatted: 7708
    # ------------------------------------------------------
    # LIMA dataset, human written, for general chat.
    # Some instances were filtered in building Tulu 2, probably due to some identity keywords.
    # Total: 1018
    # Pro: created by researchers at Meta, aiming for diversity and high quality.
    # Con: small, they were created quite early so might not consider some of the latest answering styles of chatbot.
    # natolambert/tulu-v2-sft-mixture-lima: 1018
    # ------------------------------------------------------
    # Aya dataset, human written, for general chat (multilingual).
    # Total: 202362
    # Pro: created by ..., aiming for very diverse languages ().
    # Con: answers may not be in the perfect style.
    ai2-adapt-dev/aya_dataset-reformat: 202362
    # ------------------------------------------------------
    # SlimOrca dataset, gpt4 generated, for general chat.
    # Total: 517982
    # Pro: Paring FLAN v2 inputs with system prompts, and regenerating the outputs using GPT4, potentially in a better style.
    # Con: GPT4 responses may contain errors, which may be mitagated by the filtering in SlimOrca
    # TODO: need to need to ablate and compare with the 300K one Faeze created. may benefit from regeneration.
    # ai2-adapt-dev/slim-orca-300k: 100000
    ai2-adapt-dev/SlimOrca-reformat: 100000
    # ------------------------------------------------------
    # WizardLM eval instruct dataset, gpt4 generated, for general chat.
    # Total: 196000
    # Pro: the approach deepens the complexity of gpt4-generated data
    # Con: GPT4 generations have eorrs, may also inheritate the biases/styles in GPT4
    # TODO: need to ablate.
    WizardLMTeam/WizardLM_evol_instruct_V2_196k: 30000
    # ------------------------------------------------------
    # WildChat dataset, real user queries + gpt4 responses, for general chat.
    # Total: 254663 (1M if including those interacting with gpt 3.5)
    # Pro: real user queries, may contain diverse challenging scenarios, as well as unsafe prompts. Mutli-turn.
    # Con: user queries are usually not that well-formated, and contain a lot of noises.
    ai2-adapt-dev/WildChat-1M-Full-GPT4-Only: 254663
    # ------------------------------------------------------
    # Daring-Anteater, a mix of existing datasets, for general chat.
    # Total: 99532
    # Pro: a good mix of precise_instruction_following / json_format_following / complex instructions.
    # Con: the constraint following part is too small.
    # TODO: need to ablate if exclusing the main chat subset is helpful.
    # TODO: data needs to be reformatted to consider the system prompt.
    ai2-adapt-dev/Daring-Anteater-reformat: 99532
    # ------------------------------------------------------
    # WebInstruct dataset, extract&rewritten using gpt4, (mainly) for math/science related questions
    # Here, we are using their released subset.
    # Total: 2335220
    # Pro: the generation benefits from GPT4 answering style & the correctness of grounding to web documents.
    # Con: may be biased by the response styles in the three websites (MathStackExchange, ScienceStackExchange, Socratic);
    #      the question answering style are also not diverse enough, with different instruction constraints;
    #      the answer may still have some errors (10% based on the paper)
    # TODO: need to ablate the effect.
    ai2-adapt-dev/WebInstructSub-reformat: 100000