# model_name_or_path: ai2-adapt-dev/OLMo-medium-peteish7-anneal-from-928646-50B-nowup-dclm07-flan
model_name_or_path: /adapt-data/ai2-llm/checkpoints/OLMo-medium/peteish7-anneal-from-928646-50B-nowup-dclm07-fw2/step11931-hf
model_revision: main
use_flash_attn: true
# tokenizer_name: ai2-adapt-dev/OLMo-medium-peteish7-anneal-from-928646-50B-nowup-dclm07-flan
tokenizer_name: /adapt-data/ai2-llm/checkpoints/OLMo-medium/peteish7-anneal-from-928646-50B-nowup-dclm07-fw2/step11931-hf
use_slow_tokenizer: false # olmo models only use fast tokenizers
dataset_mixer:
    ai2-adapt-dev/metamath-qa-reformat: 1.0 # MIT License
    nvidia/Daring-Anteater: 1.0 # CC BY 4.0, 
    natolambert/tulu-v2-sft-mixture-flan: 1.0 # FLAN Apache 2.0
    natolambert/tulu-v2-sft-mixture-cot: 1.0 # FLAN Apache 2.0
    Open-Orca/OpenOrca: .02 # MIT
    allenai/openassistant-guanaco-reformatted: 1.0 # Apache 2.0
    ai2-adapt-dev/codefeedback-single-turn-reformat-magicoder: 1.0 # MIT MagiCoder section of CodeFeedback
max_seq_length: 4096
preprocessing_num_workers: 128
per_device_train_batch_size: 1 # note, this is set up for 8 GPUs
gradient_accumulation_steps: 4 # designed for 4 nodes
learning_rate: 2.0e-06
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 3
output_dir: /output/olmo_instruct/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: epoch
add_bos: true