# model_name_or_path: ai2-adapt-dev/OLMo-medium-peteish7-anneal-from-928646-50B-nowup-dclm07-flan
model_name_or_path: /adapt-data/ai2-llm/checkpoints/OLMo-medium/peteish7-anneal-from-928646-50B-nowup-dclm07-fw2/step11931-hf
model_revision: main
use_flash_attn: true
# tokenizer_name: ai2-adapt-dev/OLMo-medium-peteish7-anneal-from-928646-50B-nowup-dclm07-flan
tokenizer_name: /adapt-data/ai2-llm/checkpoints/OLMo-medium/peteish7-anneal-from-928646-50B-nowup-dclm07-fw2/step11931-hf
use_slow_tokenizer: false # olmo models only use fast tokenizers
dataset_mixer:
    ai2-adapt-dev/metamath-qa-reformat: 1.0 # MIT License
    natolambert/tulu-v2-sft-mixture-flan: 1.0 # FLAN Apache 2.0
    natolambert/tulu-v2-sft-mixture-cot: 1.0 # FLAN Apache 2.0
    allenai/openassistant-guanaco-reformatted: 1.0 # Apache 2.0
    ai2-adapt-dev/codefeedback-single-turn-reformat-magicoder: 1.0 # MIT MagiCoder section of CodeFeedback
    ai2-adapt-dev/aya_dataset-reformat: 1.0 # Apache 2.0
    ai2-adapt-dev/SlimOrca-reformat: 0.25 # MIT License
    ai2-adapt-dev/Daring-Anteater-reformat: 1.0 # CC BY 4.0
    ai2-adapt-dev/WebInstructSub-reformat-apache: 0.1 # Apache 2.0
    ai2-adapt-dev/Table-GPT-All-train: 0.5 # MIT
max_seq_length: 4096
preprocessing_num_workers: 128
per_device_train_batch_size: 1
gradient_accumulation_steps: 4 # designed for 4 nodes
# gradient_accumulation_steps: 16 # designed for 1 nodes
gradient_checkpointing: true
learning_rate: 2.0e-06
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 3
output_dir: /output/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: epoch
add_bos: true