model_name_or_path: meta-llama/Meta-Llama-3.1-8B
model_revision: main
use_flash_attn: true
tokenizer_name: meta-llama/Meta-Llama-3.1-8B
use_slow_tokenizer: true
dataset_mixer:
    jacobmorrison/rejection_sampling_9350: 9495
    # HuggingFaceH4/no_robots: 9500

    jacobmorrison/rejection_sampling_3686: 7538
    # allenai/openassistant-guanaco-reformatted: 7708

    jacobmorrison/rejection_sampling_4906: 200092
    # ai2-adapt-dev/aya_dataset-reformat: 202362

    # jacobmorrison/rejection_sampling_1117: 14
    ai2-adapt-dev/tulu_hard_coded_examples: 14

    # jacobmorrison/rejection_sampling_6086: 9910
    ai2-adapt-dev/SciRIFF-train-mix-science: 10000

    jacobmorrison/rejection_sampling_6511: 98860
    # ai2-adapt-dev/SlimOrca-reformat: 100000

    jacobmorrison/rejection_sampling_26712: 29988
    # WizardLMTeam/WizardLM_evol_instruct_V2_196k: 30000

    jacobmorrison/rejection_sampling_943: 235448
    # ai2-adapt-dev/WildChat-1M-Full-GPT4-Only: 254663

    # jacobmorrison/rejection_sampling_19367: 99288
    ai2-adapt-dev/Daring-Anteater-reformat: 99532

    # jacobmorrison/rejection_sampling_3379: 98953
    ai2-adapt-dev/metamath-qa-reformat: 100000

    jacobmorrison/rejection_sampling_2413: 99988
    # ai2-adapt-dev/WebInstructSub-reformat: 100000

    # jacobmorrison/rejection_sampling_22710: 156184
    m-a-p/CodeFeedback-Filtered-Instruction: 156526

    # jacobmorrison/rejection_sampling_5816: 2395
    ai2-adapt-dev/Table-GPT-All-train: 3000

    # jacobmorrison/rejection_sampling_4424: 11477
    ai2-adapt-dev/coconot-sft-reformat: 11477

    # jacobmorrison/rejection_sampling_1215: 72425
    AI-MO/NuminaMath-TIR: 72441
max_seq_length: 4096
preprocessing_num_workers: 128
per_device_train_batch_size: 1 # note, this is set up for 8 GPUs
gradient_accumulation_steps: 8 # effective batch size 128 with 4 nodes
learning_rate: 5.0e-06 # best LR so far
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 2
output_dir: /output/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: epoch
dataset_mix_dir: /output/
