model_name_or_path: deepseek-ai/deepseek-math-7b-base
model_revision: main
use_flash_attn: true
tokenizer_name: deepseek-ai/deepseek-math-7b-base
use_slow_tokenizer: true
dataset_mixer:
    # Tulu 2 datasets (removed):
    natolambert/tulu-v2-sft-mixture-flan: 50000
    natolambert/tulu-v2-sft-mixture-cot: 49747
    Vtuber-plan/sharegpt-cleaned: 114046  # original https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered
    vicgalle/alpaca-gpt4: 20000
    HuggingFaceH4/CodeAlpaca_20K: 18000  # original uses https://github.com/sahil280114/codealpaca
    natolambert/tulu-v2-sft-mixture-lima: 1018  # original has 1030
    natolambert/tulu-v2-sft-mixture-science: 7468  # original data slightly different

    # Tulu 2 datasets (kept):
    allenai/openassistant-guanaco-reformatted: 7708  # not exact subset
    WizardLMTeam/WizardLM_evol_instruct_V2_196k: 30000
    Open-Orca/OpenOrca: 30000

    # Numina:
    AI-MO/NuminaMath-TIR: 72441

    # Faeze's datasets:
    # ai2-adapt-dev/numina_math_gsm8k_prefs_balance_minerva_format_v2_messages_format: 22841
    # ai2-adapt-dev/math_numina_balanced_none_mc_prefs_minerva_format_messages_format: 41603
max_seq_length: 4096 # Note, reduced from 8192 to fit on one GPU with DeepSpeed Stage3
preprocessing_num_workers: 128
per_device_train_batch_size: 1 # note, this is set up for 8 GPUs
gradient_accumulation_steps: 4 # effective batch size 128 with 4 nodes
learning_rate: 5.0e-06 # best LR so far
lr_scheduler_type: linear
warmup_ratio: 0.03                                    
weight_decay: 0.0
num_train_epochs: 2
output_dir: /output/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: epoch
dataset_mix_dir: /output/
