model_name_or_path: meta-llama/Meta-Llama-3.1-8B
model_revision: main
use_flash_attn: true
tokenizer_name: meta-llama/Meta-Llama-3.1-8B
use_slow_tokenizer: true
dataset_mixer:
    # # ------------------------------------------------------
    # # no_robot dataset, human written, for general chat. 
    # # Total: 9500
    # # Pro: created by surge ai with high cost, should be high quality.
    # # Con: small, not diverse enough, may not be in consistent style.
    # HuggingFaceH4/no_robots: 9500
    # # ------------------------------------------------------
    # # SlimOrca dataset, gpt4 generated, for general chat.
    # # Total: 517982
    # # Pro: Paring FLAN v2 inputs with system prompts, and regenerating the outputs using GPT4, potentially in a better style.
    # # Con: GPT4 responses may contain errors, which may be mitagated by the filtering in SlimOrca
    # # TODO: need to need to ablate and compare with the 300K one Faeze created. may benefit from regeneration.
    # # ai2-adapt-dev/slim-orca-300k: 100000
    # ai2-adapt-dev/SlimOrca-reformat: 100000
    # # ------------------------------------------------------
    # # WizardLM eval instruct dataset, gpt4 generated, for general chat.
    # # Total: 196000
    # # Pro: the approach deepens the complexity of gpt4-generated data
    # # Con: GPT4 generations have eorrs, may also inheritate the biases/styles in GPT4
    # # TODO: need to ablate.
    # WizardLMTeam/WizardLM_evol_instruct_V2_196k: 30000
    # ------------------------------------------------------
    # WildChat dataset, real user queries + gpt4 responses, for general chat.
    # Total: 254663 (1M if including those interacting with gpt 3.5)
    # Pro: real user queries, may contain diverse challenging scenarios, as well as unsafe prompts. Mutli-turn.
    # Con: user queries are usually not that well-formated, and contain a lot of noises.
    ai2-adapt-dev/WildChat-1M-Full-GPT4-Only: 254663
    # # ------------------------------------------------------
    # # Daring-Anteater, a mix of existing datasets, for general chat.
    # # Total: 99532
    # # Pro: a good mix of precise_instruction_following / json_format_following / complex instructions.
    # # Con: the constraint following part is too small.
    # # TODO: need to ablate if exclusing the main chat subset is helpful.
    # # TODO: data needs to be reformatted to consider the system prompt.
    # ai2-adapt-dev/Daring-Anteater-reformat: 99532
    # ------------------------------------------------------
    # NuminaMATH-TIR, extracted and generated by gpt4, for tool-integrated reasoning for math
    # Total: 72441
    # Pro: generally high-quality dataset with mined prompts from web corpus, verified tool-integrated reasoning trajatories.
    # Con: mainly for solving math in a specific format, not in a consistent format with the general chat.
    # TODO: need to ablate. need to rewrite!!!
    AI-MO/NuminaMath-TIR: 72441
max_seq_length: 4096 # Note, reduced from 8192 to fit on one GPU with DeepSpeed Stage3
preprocessing_num_workers: 128
per_device_train_batch_size: 1 # note, this is set up for 8 GPUs
gradient_accumulation_steps: 4 # effective batch size 128 with 4 nodes
learning_rate: 5.0e-06 # best LR so far
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 2
output_dir: /output/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: epoch
dataset_mix_dir: /output/
