model_name_or_path: /model
tokenizer_name: /model
model_revision: main
use_flash_attn: true
gradient_checkpointing: true
dataset_mixer:
  ai2-adapt-dev/sft_v3.9_used_off_policy: 1.0
  ai2-adapt-dev/wildchat_v3.9_unused_off_policy: 1.0
  ai2-adapt-dev/sft_v3.9_used_p0_olmoe-1b-7b: 1.0
  ai2-adapt-dev/sft_v3.9_used_p1_olmoe-1b-7b: 1.0
  ai2-adapt-dev/daring_anteater_olmoe-1b-7b: 1.0
  ai2-adapt-dev/wildchat-prefs-280824_olmoe-1b-7b: 1.0
  ai2-adapt-dev/wildchat_v3.9_unused_p0_olmoe-1b-7b: 1.0
  # ai2-adapt-dev/sft_v3.9_used_on_policy_large_70b_ckpt: 1.0
  # ai2-adapt-dev/WildChat-prefs-280824-uf-pipeline-regen-v3.9_large_70b_ckpt: 1.0
  # ai2-adapt-dev/Llama-3.1-if_taxonomy_tulu-uf-pipeline-regen-v3.9_large_70b_ckpt: 1.0
  # ai2-adapt-dev/wildchat_v3.9_used_on_policy_large_70b_ckpt: 1.0
  # ai2-adapt-dev/ultrafeedback-cleaned-regen-v3.9-70b-sft: 1.0
  # orig ultrafeedback below (no sharegpt)
  # ai2-adapt-dev/tulu-2.5-prefs-ultrafeedback_ultrachat: 1.0
  # ai2-adapt-dev/tulu-2.5-prefs-ultrafeedback_truthful_qa: 1.0
  # ai2-adapt-dev/tulu-2.5-prefs-ultrafeedback_flan_v2: 1.0
  # ai2-adapt-dev/tulu-2.5-prefs-ultrafeedback_false_qa: 1.0
use_slow_tokenizer: false
max_seq_length: 2048
preprocessing_num_workers: 16
# designed for 32 GPUs, so batch size 32
per_device_train_batch_size: 1
gradient_accumulation_steps: 1 
learning_rate: 5.0e-7
lr_scheduler_type: linear
warmup_ratio: 0.1
weight_decay: 0.0
num_train_epochs: 1
output_dir: /output
with_tracking: true
report_to:
  - wandb
logging_steps: 1
use_lora: false
dpo_loss_type: dpo_norm
dpo_beta: 5
checkpointing_steps: epoch