merge_method: linear
normalize: true
models:
  - name: llama_3_8b-rs_30566_v3.2_more_rs
    location: beaker
    path: jacobm/llama_3_8b-rs_30566_v3.2_more_rs
    weight: 0.5
  - name: llama_3_8b-rs_30566_numina
    location: beaker
    path: jacobm/llama_3_8b-rs_30566_numina
    weight: 0.5