merge_method: linear
normalize: true
models:
  - name: L38B-rs_2860_v3.2-dpo_norm_beta5_uf_1ep
    location: beaker
    path: jacobm/L38B-rs_2860_v3.2-dpo_norm_beta5_uf_1ep
    weight: 0.6
  - name: L38B-rs_2860_numina-dpo_norm_beta5_uf_1ep
    location: beaker
    path: jacobm/L38B-rs_2860_numina-dpo_norm_beta5_uf_1ep
    weight: 0.4