merge_method: linear
normalize: true
models:
  - name: L38B-rs_2860_v3.2_more_rs
    location: beaker
    path: jacobm/L38B-rs_2860_v3.2_more_rs
    weight: 0.6
  - name: L38B-rs_2860_numina
    location: beaker
    path: jacobm/L38B-rs_2860_numina
    weight: 0.4