merge_method: linear
normalize: true
models:
  - name: deepseek-math-7b-math-attempt-3
    location: beaker
    path: jacobm/deepseek-math-7b-math-attempt-3
    weight: 0.5
  - name: deepseek-coder-7b-math-attempt-3
    location: beaker
    path: jacobm/deepseek-coder-7b-math-attempt-3
    weight: 0.5