merge_method: task_arithmetic
base_model: ai2-adapt-dev/llama-3.1-8b-resized
normalize: true
models:
  # - name: deepseek-math-7b-instruct
  #   location: huggingface
  #   path: deepseek-ai/deepseek-math-7b-instruct
  #   weight: 0.5
  # - name: deepseek-coder-7b-instruct-v1.5
  #   location: huggingface
  #   path: deepseek-ai/deepseek-coder-7b-instruct-v1.5
  #   weight: 0.5
  - name: L3.1-8B-v3.8-nc-final
    location: weka
    path: /oe-adapt-default/jacobm/tulu-3-dev/checkpoints/base_models/L3.1-8B-v3.8-nc-final/
    wekaBucket: "oe-adapt-default"
    weight: 1.0
  - name: L3.1-8B-v3.8-math_subset
    location: weka
    path: /oe-adapt-default/jacobm/tulu-3-dev/checkpoints/base_models/L3.1-8B-v3.8-math_subset/
    wekaBucket: "oe-adapt-default"
    weight: 0.46