model_name_or_path: ai2-adapt-dev/OLMo-medium-peteish7-anneal-from-928646-50B-nowup-dclm07-flan
model_revision: main
use_flash_attn: true
tokenizer_name: ai2-adapt-dev/OLMo-medium-peteish7-anneal-from-928646-50B-nowup-dclm07-flan
use_slow_tokenizer: false # olmo models only use fast tokenizers
dataset_mixer:
  ai2-adapt-dev/synthetic-cot-wildguarmixtrain: 86759
  ai2-adapt-dev/tulu_v3.9_wildjailbreak_decontaminated_unused: 209574 # all
max_seq_length: 4096
preprocessing_num_workers: 128
per_device_train_batch_size: 1
gradient_accumulation_steps: 8 # should run with this set to 16 for 1 node only
learning_rate: 2.0e-06
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 3
output_dir: /output/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: epoch
add_bos: true