model_name_or_path: /oe-adapt-default/jacobm/tulu-3-dev/checkpoints/base_models/L3.1-70B-v3.9-nc-2e-6-2_ep-fixed/
tokenizer_name: /oe-adapt-default/jacobm/tulu-3-dev/checkpoints/base_models/L3.1-70B-v3.9-nc-2e-6-2_ep-fixed/
model_revision: main
use_flash_attn: true
gradient_checkpointing: true
# dataset_name: ai2-adapt-dev/tulu3.4-sft-replica-50k
# dataset_config_name: gpt4-prefs-on-policy
dataset_mixer:
  # Ultrafeedback
  #allenai/ultrafeedback_binarized_cleaned_train: 1.0
  # LJ's UF regenerations old
  #ai2-adapt-dev/tulu3.4-sft-replica-50k-gpt4-prefs-on-policy: 1.0
  # LJ's Helpsteer2 regenerations
  ai2-adapt-dev/helpsteer2-uf-pipeline-regen: 1.0
  #LJ's UF regenerations
  ai2-adapt-dev/sft_v3.9_used_off_policy: 1.0
  ai2-adapt-dev/sft_v3.9_used_on_policy_large_70b_ckpt: 1.0
  #LJ's regenerations of my datasets
  ai2-adapt-dev/DaringAnteater-prefs-RM-filter-uf-pipeline-regen-v3.9_large_70b_ckpt: 1.0
  ai2-adapt-dev/WildChat-prefs-280824-uf-pipeline-regen-v3.9_large_70b_ckpt: 1.0
  ai2-adapt-dev/Llama-3.1-if_taxonomy_tulu-uf-pipeline-regen-v3.9_large_70b_ckpt: 1.0
  #LJ's unused WildChat regenerations
  ai2-adapt-dev/wildchat_v3.9_unused_off_policy: 1.0
  #Faeze's persona IF preference dataset
  #ai2-adapt-dev/personahub_if_pref_data_manualseed_v2_19890: 1.0
  # Add Ultrafeedback cleaned regen
  #ai2-adapt-dev/ultrafeedback-cleaned-regen-v3.9: 1.0
use_slow_tokenizer: true
max_seq_length: 2048
preprocessing_num_workers: 16
per_device_train_batch_size: 1
gradient_accumulation_steps: 2 # designed for 8 GPUs, so batch size 128
learning_rate: 2.0e-7
lr_scheduler_type: linear
warmup_ratio: 0.1
weight_decay: 0.0
num_train_epochs: 1
output_dir: /output
with_tracking: true
report_to:
  - wandb
logging_steps: 1
use_lora: false
dpo_loss_type: dpo_norm
dpo_beta: 5
checkpointing_steps: epoch