model_name_or_path: /oe-adapt-default/jacobm/tulu-3-dev/checkpoints/base_models/L3.1-70B-v3.8-lr_2e-6-2_epochs
model_revision: main
use_flash_attn: true
gradient_checkpointing: true
# dataset_name: ai2-adapt-dev/tulu3.4-sft-replica-50k
# dataset_config_name: gpt4-prefs-on-policy
dataset_mixer:
  ai2-adapt-dev/tulu3.4-sft-replica-50k-gpt4-prefs-on-policy: 1.0
  ai2-adapt-dev/personahub_if_pref_data_manualseed_v2_19890: 1.0
tokenizer_name: /oe-adapt-default/jacobm/tulu-3-dev/checkpoints/base_models/L3.1-70B-v3.8-lr_2e-6-2_epochs
use_slow_tokenizer: true
max_seq_length: 2048
preprocessing_num_workers: 16
per_device_train_batch_size: 1
gradient_accumulation_steps: 2 # designed for 8 GPUs, so batch size 128
learning_rate: 5.0e-7
lr_scheduler_type: linear
warmup_ratio: 0.1
weight_decay: 0.0
num_train_epochs: 1
output_dir: /output
with_tracking: true
report_to:
  - wandb
logging_steps: 1
use_lora: false
dpo_loss_type: dpo_norm
dpo_beta: 5
checkpointing_steps: epoch